name: Erlang CI

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        erlang: [24, 25]

    container:
      image: erlang:${{matrix.erlang}}

    steps:
    - uses: actions/checkout@v3
    - name: compile and test
      run: rebar3 check
